version: '3'

services:
#  postgresql:
#    restart: always
#    image: postgres:10
#    container_name: postgresql
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: us_car_ga
#      POSTGRES_USER: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql

  site:
    build: ./data/Dockerfile
    restart: always
    image: site:latest
    container_name: site
    expose:
      - 5000
    labels:
      - "traefik.backend=site"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:uscar.ga"
      - "traefik.enable=true"
    networks:
      - traefik
    volumes:
      - ./data:/var/www/site
    entrypoint: python
    command: run.py
    working_dir: /var/www/site

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - "194.67.205.188:80:80"
      - "194.67.205.188:443:443"
    container_name: traefik
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/traefik.toml
      - ./data/acme.json:/acme.json
    container_name: traefik

networks:
  traefik:
    external: true

