debug = false
checkNewVersion = true
logLevel = "INFO"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "boomplex.com"
watch = true
exposedByDefault = false

[acme]
email = "max@2327.ru"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = true
acmeLogging = true
#caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [acme.httpChallenge]
  entryPoint = "http"

